FROM node:20-alpine AS builder

WORKDIR /app

COPY apps/b2b-console/package*.json ./
RUN npm install

COPY apps/b2b-console/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY apps/b2b-console/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
