-- SARATHI core schema
-- Smart Autonomous Routing & Adaptive Tourism Hospitality Intelligence
-- Extensions -----------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ENUMS ------------------------------------------------------------------
CREATE TYPE poi_category AS ENUM (
    'heritage', 'nature', 'religious', 'adventure', 'shopping',
    'food', 'museum', 'viewpoint', 'entertainment', 'wellness'
);

CREATE TYPE crowd_level AS ENUM ('low', 'moderate', 'high', 'severe');

CREATE TYPE booking_status AS ENUM (
    'pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'no_show'
);

CREATE TYPE user_role AS ENUM ('tourist', 'hotelier', 'admin', 'guide');

-- CORE TABLES --------------------------------------------------------------

-- Destinations / cities SARATHI operates in
CREATE TABLE destinations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(120) NOT NULL,
    state VARCHAR(80) NOT NULL,
    country VARCHAR(80) NOT NULL DEFAULT 'India',
    centroid GEOGRAPHY(POINT, 4326) NOT NULL,
    bounding_box GEOGRAPHY(POLYGON, 4326),
    timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Kolkata',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Points of interest
CREATE TABLE points_of_interest (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    destination_id UUID NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    category poi_category NOT NULL,
    location GEOGRAPHY(POINT, 4326) NOT NULL,
    avg_visit_minutes INTEGER NOT NULL DEFAULT 45,
    max_capacity INTEGER,               -- for crowd-safety capping
    opening_time TIME,
    closing_time TIME,
    entry_fee_inr NUMERIC(10,2) DEFAULT 0,
    languages_supported TEXT[] DEFAULT ARRAY['en', 'hi'],
    metadata JSONB DEFAULT '{}'::jsonb, -- flexible attrs: accessibility, tags, etc.
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_poi_location ON points_of_interest USING GIST (location);
CREATE INDEX idx_poi_destination ON points_of_interest (destination_id);
CREATE INDEX idx_poi_category ON points_of_interest (category);

-- Hourly footfall observations/predictions per POI (feeds Prophet/LightGBM)
CREATE TABLE footfall_records (
    id BIGSERIAL PRIMARY KEY,
    poi_id UUID NOT NULL REFERENCES points_of_interest(id) ON DELETE CASCADE,
    observed_at TIMESTAMPTZ NOT NULL,
    footfall_count INTEGER NOT NULL,
    crowd_level crowd_level,
    is_synthetic BOOLEAN NOT NULL DEFAULT false,  -- true for seeded/synthetic data
    is_forecast BOOLEAN NOT NULL DEFAULT false,   -- true if model-predicted vs observed
    source VARCHAR(50) DEFAULT 'synthetic',       -- e.g. 'synthetic', 'sensor', 'app_checkins'
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_footfall_poi_time ON footfall_records (poi_id, observed_at);
CREATE INDEX idx_footfall_time ON footfall_records (observed_at);

-- Hoteliers / properties
CREATE TABLE properties (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    destination_id UUID NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
    owner_user_id UUID,
    name VARCHAR(200) NOT NULL,
    location GEOGRAPHY(POINT, 4326) NOT NULL,
    total_rooms INTEGER NOT NULL DEFAULT 1,
    star_rating SMALLINT CHECK (star_rating BETWEEN 1 AND 5),
    amenities TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_properties_location ON properties USING GIST (location);

-- Room-level daily occupancy/pricing (feeds demand forecasting per property)
CREATE TABLE occupancy_records (
    id BIGSERIAL PRIMARY KEY,
    property_id UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    rooms_booked INTEGER NOT NULL DEFAULT 0,
    avg_daily_rate_inr NUMERIC(10,2),
    is_synthetic BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (property_id, date)
);

-- Users (tourists, hoteliers, admins, guides)
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    role user_role NOT NULL DEFAULT 'tourist',
    full_name VARCHAR(150),
    email VARCHAR(150) UNIQUE,
    phone VARCHAR(20),
    preferred_language VARCHAR(10) DEFAULT 'en',
    home_location GEOGRAPHY(POINT, 4326),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE properties
    ADD CONSTRAINT fk_owner_user FOREIGN KEY (owner_user_id) REFERENCES users(id);

-- Trip plans generated by the TD-VRPTW engine
CREATE TABLE trip_plans (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    destination_id UUID NOT NULL REFERENCES destinations(id),
    trip_date DATE NOT NULL,
    start_location GEOGRAPHY(POINT, 4326) NOT NULL,
    preferences JSONB DEFAULT '{}'::jsonb, -- interests, budget, pace, mobility constraints
    optimized_route JSONB NOT NULL,        -- ordered POI sequence with ETAs (solver output)
    total_distance_km NUMERIC(8,2),
    total_duration_minutes INTEGER,
    status VARCHAR(30) DEFAULT 'draft',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_trip_plans_user ON trip_plans (user_id);
CREATE INDEX idx_trip_plans_date ON trip_plans (trip_date);

-- Bookings linking tourists to properties/time windows
CREATE TABLE bookings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    property_id UUID NOT NULL REFERENCES properties(id),
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    rooms INTEGER NOT NULL DEFAULT 1,
    status booking_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_bookings_property_dates ON bookings (property_id, check_in, check_out);

-- Real-time crowd/alert events (fed to WebSocket layer)
CREATE TABLE realtime_events (
    id BIGSERIAL PRIMARY KEY,
    poi_id UUID REFERENCES points_of_interest(id) ON DELETE CASCADE,
    event_type VARCHAR(50) NOT NULL,   -- 'crowd_spike', 'closure', 'weather_alert', etc.
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_realtime_events_poi_time ON realtime_events (poi_id, created_at);
